 
name: CS7641_A2
dependencies:
- python=3.6
- scikit-learn=0.22.1
- matplotlib=3.0.3
- pandas=0.24.2
- seaborn=0.9.0
- pip
- pip:
  - pprofile==2.0.2
  - jsons==0.8.8
  - mlrose==1.3.0
    #  - git+git://github.com/hiive/mlrose#egg=mlrose-hiive
